site:
  title: Antora Docs
  start_page: component-b::index.adoc 
content:
  sources: 
  - url: https://github.com/smilovanov-5am/Lokeo.Docs.git
    branches: HEAD
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true